= Kubernetes Provisioning Tool
Eichhorn M., Polleichtner M., Sljivic E., Wallinger M.
1.0.0, 2020-10-10
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Project Title
Kubernetes Provisioning Tool

== Project Client
HTL Leonding

== Project Background
Many popular cloud services (Azure, IBM, Google Cloud) are too expensive for educational purpose. Also, offers like "free for X hours" often include hidden costs - this just isn't suitable for our use case.
Starting with the third grade, most classes are in the need for one or multiple hosted Docker containers for their projects, but this is currently hard to manage,
because everyone has to do it on their own, or they have to contact a teacher who assists them with their project.

== Project Result
There will be a website where the students can log in with their LDAP credentials and request a cluster by filling out a template or by submitting an own specification (yaml file). The own specifications have to be approved by a teacher.
Teachers are able to create templates (these include %variables% to let students configure services and other configuration options).
Kubernetes automatically handles the creation of the cluster.

== Project Goals
The goal of this project is that students can easily create a k8s working environment for their projects.

== Milestones
* Figure out how to use the KVM switch
* Install new operating system on servers
* Get current state of project running on the servers

== Project Start
This team will be starting to work on this project on Mon, 19.10. 2020, but another team has been working on the project since March 2020.

== Project End
The intended end of this project for this team would be the end of the fifth grade (May 2022).

== Project Resources
* 3 Servers
* Raritan, Dominion LX2-108 (KVM-over-IP Switch)

== Project Organisation
=== 5AHITM
* Halil Bahar **(Project leader)**
* Sonja Cao

=== 4AHIF
* Moritz Eichhorn
* Moritz Polleichtner
* Emina Sljivic
* Marc Wallinger